# Generated by Django 4.2.8 on 2024-11-01 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositproducts',
            old_name='exc_note',
            new_name='etc_note',
        ),
    ]
