# Generated by Django 4.2.8 on 2024-11-01 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0002_rename_exc_note_depositproducts_etc_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='intr_rate',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='depositoptions',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option', to='finlife.depositproducts'),
        ),
    ]
