# Generated by Django 4.2.11 on 2024-11-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0003_alter_depositoptions_intr_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositoptions',
            name='intr_rate',
            field=models.FloatField(null=True),
        ),
    ]
